frontend/src/Components/Top_group_picker_components/AddGroup.svelte
frontend/src/Components/Top_group_picker_components/GroupPickerContainer.svelte

Added an "Add Group" button that opens a modal. Other than that - no functionality

:flushed: Add GroupBtn

---

backend/app/api/init_api.py
backend/app/db.py

* Increment pragma user_version after applying migration.
* Enable logging

Database: Load migrations during startup

---

frontend/package-lock.json
frontend/package.json
frontend/src/Components/PunishmentDisplay/AddNewPunishment.svelte
frontend/src/Components/PunishmentDisplay/PunishmentInfo.svelte
frontend/src/api.ts
frontend/src/types.ts
frontend/tailwind.config.cjs

Adds fields and btn for adding new punishment to user. Users can add a reason, choose a punishment and choose how many punishments should be added.
Closes #13

13 multiple punishments

---

frontend/src/Components/PunishmentDisplay/PunishmentInfo.svelte
frontend/src/api.ts

Can now verify and delete punishments.
Verified punishments show a text describing who verified them.
Closes #23

23 register and delete

---

frontend/src/Components/Top_group_picker_components/Navbar.svelte

Updates navbar.
Removes color of btns, bit janky but works for now8)
Closes #95

:lipstick: #95 Update navbar style + btns

---

frontend/src/Components/Filters/Time/DateTimeFilters.svelte

Time picker component now checks that user actually picks time filter before nullifying other time filter.
Closes #98

:bug: #98 Fixed time filter bug

---

.github/workflows/pull_request_template.md

:memo: Add PR template

---

backend/Makefile

Removed functions in makefile

---

backend/app/db.py

Fixed user punishments not showing up on get_group_user

---

frontend/index.html
frontend/src/components/filters/Sidebar.svelte
frontend/src/stores/punishmentToFilter.ts
frontend/src/stores/users.ts
frontend/vite.config.js

Fixed all the frontend bugs that I've encountered so far.

Fix frontend bugs

---

frontend/src/stores/users.ts

The user search bar also correctly filters on upper/lowercase + firstname + lastname
Closes #111

:bug: (#111) Fix user search filter

---

frontend/src/App.svelte
frontend/src/components/newPunishmentMultiple/NewPunishmentBtn.svelte
frontend/src/components/newPunishmentMultiple/PunishMultiple.svelte
frontend/src/components/punishments/AddNewPunishment.svelte
frontend/src/components/punishments/PunishmentInfo.svelte

Can now punish multiple users in a group. Made minor changes to the AddNewPunishment component from the grid so that it could be reused here.
Closes #79

✨ #79 Punish multiple users

---

frontend/package.json
frontend/src/components/punishments/PunishmentInfo.svelte
frontend/src/lib/types.ts

PunishmentInfo now displays who the punishment was given by and who verified it, in addition to which date it was verified:
Closes #94

✨ #94 add verified by/created by name + date

---

frontend/src/components/punishments/PunishmentInfo.svelte
frontend/src/lib/types.ts

Displays tooltip saying one can not verify one's own punishments if the ow_user_id of the user's punishment to verify is the same as the user who is logged in:
Closes #150

✨ #150 users can not verify own punishments

---

backend/app/api/endpoints/user.py
backend/app/db.py
backend/app/models/leaderboard.py
backend/app/utils/pagination.py
backend/tests/response_time.py
backend/tests/test_ow.py

- Added endpoint `/user/leaderboard` to get wall of shame.
#170

Add users leaderboard endpoint

---

.github/workflows/python-app.yml
README.md
backend/app/api/__init__.py
backend/app/api/endpoints/group.py
backend/app/api/endpoints/user.py
backend/app/db.py
backend/app/http.py
backend/app/models/group.py
backend/app/models/group_member.py
backend/app/models/group_user.py
backend/app/models/punishment.py
backend/app/models/user.py
backend/app/state.py
backend/app/sync.py
backend/app/utils/db.py
backend/app/utils/pagination.py
backend/app/utils/streaks.py
pyproject.toml

Downgraded the minimum required python version to 3.9.

Downgrade to python3.9

---

backend/app/api/__init__.py
backend/app/api/endpoints/group.py
backend/app/api/endpoints/punishment.py
backend/app/api/init_api.py
backend/tests/test_ow.py
poetry.lock
pyproject.toml

Added authentication to /docs. You can now finally actually test endpoints that require auth :))

Add authentication to /docs

---

backend/Makefile
backend/app/db/punishments.py
backend/docker-compose.yml

Fixed some issues regarding postgres docker volume and fixed punishment add endpoint.

Fix volume issue

---

frontend/src/components/stats/Stats.tsx
frontend/src/components/stats/index.tsx
frontend/src/views/hero/AuthenticatedHero.tsx

Add mock stat banner

---

frontend/src/components/table/Table.tsx
frontend/src/components/table/TableItem.tsx
frontend/src/components/table/index.tsx
frontend/src/views/leaderboard/LeaderboardView.tsx

Implement new table

---

frontend/src/components/leaderboard/Leaderboard.tsx
frontend/src/components/nav/Nav.tsx
frontend/src/components/tabs/Tabs.tsx
frontend/src/components/tabs/index.tsx
frontend/src/helpers/types.ts
frontend/src/views/leaderboard/LeaderboardView.tsx

Updated tabbar design. `frontend/src/components/leaderboard/Leaderboard.tsx` is broken (for now :p)

Implement new tab design

---

frontend/package.json
frontend/src/components/leaderboard/PunishmentItem.tsx
frontend/src/components/leaderboard/PunishmentList.tsx
frontend/src/components/table/Table.tsx
frontend/src/components/table/TableItem.tsx
frontend/src/components/table/accordion/Accordion.tsx
frontend/tailwind.config.cjs

Implement accordion

---

frontend/src/components/footer/Footer.tsx

Update footer color

---

frontend/src/components/footer/Footer.tsx
frontend/src/components/nav/Nav.tsx
frontend/src/pages/profile/AuthenticatedProfile.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/index.tsx
frontend/src/routes.tsx

Add profile page

---

frontend/src/components/nav/Nav.tsx
frontend/src/components/nav/NavLink.tsx
frontend/src/pages/wallOfShame/WallOfShame.tsx
frontend/src/pages/wallOfShame/index.tsx
frontend/src/routes.tsx

Add wall of shame page boilerplate

Add wall of shame page

---

frontend/src/components/modal/Modal.tsx
frontend/src/components/tabs/Tabs.tsx
frontend/src/views/groups/GroupsView.tsx
frontend/src/views/layout/Layout.tsx

Improved punishing

---

frontend/src/components/table/punishment/PunishmentItem.tsx
frontend/src/components/table/punishment/emojies/EmojiPicker.tsx
frontend/src/components/table/punishment/emojies/ReactionDisplay.tsx
frontend/src/helpers/api.ts
frontend/src/helpers/types.ts
frontend/src/helpers/userContext.tsx
frontend/src/views/groups/GroupsView.tsx
frontend/src/views/layout/Layout.tsx

U can now click on ur own emoji to remove it and click on others to add

Improve ui reaction logic

---

backend/Makefile

Remove dev reqs from makefile

---

backend/app/db/groups.py
backend/tests/test_ow.py
frontend/src/components/table/Table.tsx
frontend/src/components/table/TableItem.tsx
frontend/src/components/table/punishment/PunishmentItem.tsx
frontend/src/components/table/punishment/PunishmentList.tsx
frontend/src/helpers/types.ts
frontend/src/views/groups/tabs/modal/AlcoholInput.tsx
frontend/src/views/groups/tabs/modal/ModalInput.tsx

Added dynamically loaded punishment types based on the punishment given.
NOTE:
- Replaced punishment icons so you need to reset the database.

feat: add dynamic punishment types

---

frontend/src/components/table/punishment/emojies/EmojiPicker.tsx

Add favoritt emojiene til Jo 😊

---

frontend/src/components/nav/Nav.tsx

Don't show profile link until it is implemented

Remove profile link

---

frontend/src/components/table/punishment/PunishmentItem.tsx
frontend/src/components/table/punishment/emojies/EmojiPicker.tsx
frontend/src/components/table/punishment/emojies/ReactionDisplay.tsx

Fixed a race condition that led to reactions sometimes using the wrong emoji.

Fix reactions sometimes being wrong

---

frontend/src/helpers/sorting.ts
frontend/src/views/groups/GroupsView.tsx
frontend/src/views/groups/tabs/modal/Modal.tsx

I've added alphabetic sorting of groups based on short_name and sorting of group members based on, in order: sum of punishment values, first_name, last_name

Fix sorting of groups and group members

---

frontend/src/app.tsx

This should fix the need for signing in every time you open a new tab.

Store OIDC sessions in local storage

---

frontend/src/routes.tsx

I don't know if this is the best solution, but it works

Switch to hash router to avoid routing issues in deployment

---

frontend/src/components/table/punishment/emojies/ReactionDisplay.tsx

Now you can clearly see when you have and haven't reacted with an emoji

Made emoji reaction colors clearer

---

backend/app/api/endpoints/group.py
backend/app/api/endpoints/user.py
backend/app/db/group_members.py
backend/app/db/punishments.py
backend/app/db/users.py
backend/app/migrations/0001_initial_schema.sql
backend/app/sync.py
backend/app/types.py
backend/poetry.lock
backend/pyproject.toml
backend/tests/fixtures.py
backend/tests/response_time.py
backend/tests/test_ow.py
backend/tests/utils.py
frontend/src/components/input/AlcoholInput.tsx
frontend/src/components/table/TableItem.tsx
frontend/src/helpers/api.ts
frontend/src/helpers/types.ts
frontend/src/helpers/userContext.tsx
frontend/src/views/groups/tabs/modal/GivePunishmentModal.tsx
frontend/src/views/layout/Layout.tsx

The much awaited uuid refactor

refactor: use uuid instead of serial

---

frontend/src/components/button/IconButton.tsx
frontend/src/components/input/PersonSelect.tsx
frontend/src/components/input/TextInput.tsx
frontend/src/components/listbox/Listbox.tsx
frontend/src/components/menu/Menu.tsx
frontend/src/components/menu/MenuItem.tsx
frontend/src/components/table/Table.tsx
frontend/src/components/table/TableItem.tsx
frontend/src/components/toggle/MultipleToggle.tsx
frontend/src/components/toggle/MultipleToggleOption.tsx
frontend/src/components/toggle/SkeletonMultipleToggleOption.tsx
frontend/src/helpers/api.ts
frontend/src/helpers/sorting.ts
frontend/src/helpers/types.ts
frontend/src/pages/wallOfShame/WallOfShame.tsx
frontend/src/views/groups/GroupsView.tsx
frontend/src/views/groups/sidebar/GroupSettings.tsx
frontend/src/views/groups/sidebar/GroupsSidebar.tsx
frontend/src/views/groups/sidebar/SidebarSection.tsx
frontend/src/views/groups/sidebar/modal/EditGroupModal.tsx
frontend/src/views/groups/tabs/TabItem.tsx
frontend/src/views/groups/tabs/Tabs.tsx

Adds a sidebar for searching and filtering. This is also going to be useful in the future when we need to be able to put other stuff related to the currently selected group somewhere.

feat: add sidebar

---

backend/app/api/__init__.py
backend/app/api/endpoints/group.py
backend/app/api/endpoints/user.py
backend/app/api/init_api.py
backend/app/config.py
backend/app/db/core.py
backend/app/db/group_users.py
backend/app/db/groups.py
backend/app/db/permissions.py
backend/app/migrations/0001_initial_schema.sql
backend/app/models/group_user.py
backend/app/models/permission.py
backend/app/sync.py
backend/app/types.py
backend/app/utils/permissions.py
backend/poetry.lock
backend/pyproject.toml
backend/tests/fixtures.py
backend/tests/responses/ow_group_users.json
backend/tests/responses/ow_group_users_2.json
backend/tests/test_ow.py
backend/tests/test_permissions.py
frontend/src/helpers/types.ts

Adds a permission system. This is needed for custom groups that will be implemented in the future. OW groups are not affected by these permissions yet, but the sync module automatically gives owner to the leader of the group. We can mess around with it in the future if we want to.

Add permission system

---

backend/app/api/endpoints/group.py
backend/app/db/group_users.py
backend/app/db/groups.py
backend/app/db/punishment_types.py
backend/app/utils/permissions.py
backend/pylintrc
backend/tests/test_ow.py

Refactored and combined some db queries. Also fixed a bug with punishment reactions where they would not be filtered correctly in a group context.
This PR depends on #288 and is therefore a draft until that is merged.

Refactor some db queries

---

backend/app/config.py
backend/app/db/groups.py
backend/app/models/group.py
backend/app/utils/permissions.py
backend/tests/test_ow.py
backend/tests/test_regular_groups.py
frontend/src/components/table/Table.tsx
frontend/src/components/table/TableItem.tsx
frontend/src/components/table/punishment/PunishmentActionBar.tsx
frontend/src/components/table/punishment/PunishmentItem.tsx
frontend/src/helpers/permissions.ts
frontend/src/helpers/types.ts
frontend/src/views/groups/GroupsView.tsx
frontend/src/views/groups/modal/AdministerGroupJoinRequestsModal.tsx
frontend/src/views/groups/modal/EditGroupMembersModal.tsx
frontend/src/views/groups/modal/EditGroupModal.tsx
frontend/src/views/groups/modal/GivePunishmentModal.tsx
frontend/src/views/groups/sidebar/GroupJoinRequestsContainer.tsx
frontend/src/views/groups/sidebar/GroupSettings.tsx

Permissions and roles are now sent with the GET group endpoint and used by the frontend

Sync permissions between frontend and backend

---

frontend/src/components/table/TableItem.tsx

Add total unpaid amount to members

---

frontend/src/app.tsx

The openid endpoint is now the correct one all around

Change oidc endpoint to /sso

---

backend/app/db/group_users.py
backend/app/db/users.py
backend/app/models/punishment_reaction.py
backend/tests/test_ow.py

This is needed for the reaction hover display

Add created_by_name to reaction payload

---

frontend/src/components/committees/CommitteeCard.tsx

Added darkmode classes
DOT-548 https://linear.app/dotkom/issue/DOT-548/committees-statistic-dark-mode

Committee statistics page dark mode

---

README.md
frontend/deploy.sh

Against dev.vinstraff.no
Doppler secrets also updated

Update deployment by pointing to vinstraff resources

---

backend/Makefile
backend/lightsail-deploy-prod.sh
backend/lightsail-deploy-staging.sh
backend/lightsail-deploy.sh
backend/wait-for-lightsail-deploy-prod.sh
backend/wait-for-lightsail-deploy-staging.sh

u can deduplicate the scripts later if uwant

Fix scripts for production and staging deployment

---

frontend/src/components/groupusertable/GroupUserTableItem.tsx
frontend/src/components/leaderboardtable/LeaderboardTableItem.tsx

fix padding of user icon

---

frontend/env.ts
frontend/src/app.tsx
frontend/src/env.d.ts
frontend/vite.config.ts

Fix auth0 setup

---

frontend/src/pages/wallOfShame/WallOfShame.tsx

Refine and elevate the orthographic standardization of letter case.

Refine and elevate the orthographic standardization of letter case.

---

frontend/src/components/punishment/PunishmentItem.tsx
frontend/src/helpers/api.ts
frontend/src/views/groups/GroupView.tsx

Make it possible to delete a punishment if a user is moderator

feat: delete punishment for moderators

---

backend/app/db/statistics.py
frontend/src/components/committees/CommitteeCard.tsx
frontend/src/components/committees/CommitteeList.tsx
frontend/src/helpers/types.ts

- Added punishment sum this year to statistics page
- Small refactor of CommitteeCard

Add punishment sum this year to statistics page and sort on it

---

frontend/src/components/nav/Nav.tsx
frontend/src/views/hero/LandingPage.tsx

* change `Darkmode` to `Dark mode`
* update landing page content to feature `Vinstraff.no`

Update text content in nav and landing page components

---

frontend/src/components/punishment/PunishmentItem.tsx
frontend/src/helpers/api.ts

Refetching data after removing reaction 👍

Refetch data after removing reaction

---

backend/app/api/endpoints/group.py
backend/app/config.py
backend/app/db/groups.py
backend/app/migrations/0004_add_invite_code.sql
backend/app/models/group.py
backend/app/types.py
frontend/src/AuthRouterProvider.tsx
frontend/src/components/input/TextInput.tsx
frontend/src/helpers/api.ts
frontend/src/helpers/types.ts
frontend/src/helpers/utils.ts
frontend/src/views/groups/GroupView.tsx
frontend/src/views/groups/modal/AdministerGroupJoinRequestsModal.tsx
frontend/src/views/groups/modal/EditGroupModal.tsx

* Added nullable invite_code on groups 
* Admins can enable/disable invitecode
* Invitecodes are only pseudorandom and doesn't have any length requirements
* Invite links looks like this https://vinstraff.no/#/gruppe/dotkom/f84ck2nd
* Accept invite btn in groupview if invite code matches group
* Public groups are blocked from having invite codes

Pre approved invite links

---

frontend/src/AuthRouterProvider.tsx

No more `/#/` prefix on routes

Draft: Replace hashRouter with browserRouter

---

backend/app/sync.py

Appoint vinstraffansvarlig based on ow4 role

---

backend/app/db/users.py
frontend/src/components/leaderboardtable/LeaderboardTableItem.tsx
frontend/src/components/punishment/PunishmentItem.tsx
frontend/src/components/tooltip/Tooltip.tsx
frontend/src/helpers/api.ts
frontend/src/pages/wallOfShame/WallOfShame.tsx

* Show who reacted in wall of shame
* Fixed issue where wall of shame didn't recognize your reactions as yours unless you came straight from group page
* Refetch punishments after removing reaction
* Small style fix in tooltip

Show who reacted in wall of shame

---

backend/Dockerfile
backend/app/api/__init__.py
backend/app/api/endpoints/punishment.py
backend/app/api/init_api.py
backend/app/config.py
backend/app/db/core.py
backend/app/db/punishments.py
backend/app/db/users.py
backend/app/http.py
backend/app/models/user.py
backend/docker-compose.yml
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/AuthRouterProvider.tsx
frontend/src/components/nav/Nav.tsx
frontend/src/components/nav/NavLink.tsx
frontend/src/components/punishment/PunishmentItem.tsx
frontend/src/helpers/api.ts
frontend/src/helpers/types.ts
frontend/src/pages/PunishmentsLogPage.tsx

Added a page for viewing the latest punishments

Add recent punishments page

---

backend/Dockerfile
frontend/src/pages/PunishmentsLogPage.tsx

Fix overlay

---

frontend/src/components/nav/Nav.tsx

Made the whole dropdown-buttons in navbar clickable, not just the text 🤯🤯🤯

fix: made the whole dropdown-buttons clickable

---

frontend/src/components/alcoholGame/index.tsx

Slowness on phone is due to JS engine in phone is slow on start
So I implemented a performance test

Fix: Drunk testfix

---

frontend/src/components/nav/Nav.tsx

fix signout proper signout

---

frontend/src/components/punishment/PunishmentItem.tsx

always show punishment date

---

frontend/src/components/punishment/PunishmentItem.tsx

flip format

---

backend/app/db/group_users.py

Fix backend returning every punishment multiple times if user has multiple roles in a group
